### ISSUE TITLE
Remove daisyUI from plugins in tailwind.config,mjs

### ISSUE THREAD

**Issue by sadnansami** [shah-azman-sakin-alam/project#1]
Saar there is a bug.

**Comment by shah-azman-sakin-alam** [comment]
ok

**Comment by shah-azman-sakin-alam** [comment]
i dont undesrtnd?

**Comment by shah-azman-sakin-alam** [comment]
why remove??

**Comment by shah-azman-sakin-alam** [comment]
ah yes thank you, it didnt deplot to netfliy

7:37:48 PM: 18:37:48 [ERROR] [vite] x Build failed in 576ms
7:37:48 PM: [vite:css] [postcss] Cannot find module 'daisyui'
